
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.company.api_compilador;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SimbolosCup.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCup() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\105\000\002\002\004\000\002\002\007\000\002\003" +
    "\004\000\002\003\002\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\003\000\002" +
    "\004\004\000\002\004\004\000\002\004\004\000\002\004" +
    "\004\000\002\004\004\000\002\004\004\000\002\005\005" +
    "\000\002\005\007\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\021\003\000\002\021\003\000\002" +
    "\006\006\000\002\007\007\000\002\010\007\000\002\011" +
    "\010\000\002\011\012\000\002\020\005\000\002\012\010" +
    "\000\002\013\012\000\002\014\004\000\002\014\003\000" +
    "\002\015\010\000\002\016\007\000\002\016\002\000\002" +
    "\023\003\000\002\023\003\000\002\023\003\000\002\023" +
    "\003\000\002\023\003\000\002\023\003\000\002\023\003" +
    "\000\002\017\012\000\002\022\005\000\002\022\005\000" +
    "\002\022\005\000\002\022\005\000\002\022\005\000\002" +
    "\022\005\000\002\022\005\000\002\022\005\000\002\022" +
    "\005\000\002\022\005\000\002\022\005\000\002\022\005" +
    "\000\002\022\005\000\002\022\005\000\002\022\004\000" +
    "\002\022\005\000\002\022\003\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\022\003\000\002\022" +
    "\003\000\002\022\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\223\000\004\013\005\001\002\000\004\002\225\001" +
    "\002\000\004\004\006\001\002\000\004\014\007\001\002" +
    "\000\050\003\ufffe\004\ufffe\015\ufffe\016\ufffe\017\ufffe\020" +
    "\ufffe\021\ufffe\022\ufffe\023\ufffe\024\ufffe\025\ufffe\031\ufffe" +
    "\033\ufffe\037\ufffe\067\ufffe\070\ufffe\071\ufffe\072\ufffe\073" +
    "\ufffe\001\002\000\050\003\034\004\035\015\044\016\025" +
    "\017\036\020\014\021\015\022\045\023\024\024\016\025" +
    "\033\031\041\033\037\037\027\067\023\070\030\071\012" +
    "\072\032\073\011\001\002\000\004\064\224\001\002\000" +
    "\004\064\223\001\002\000\004\004\216\001\002\000\004" +
    "\004\uffeb\001\002\000\004\004\uffea\001\002\000\004\062" +
    "\212\001\002\000\054\003\ufff7\004\ufff7\015\ufff7\016\ufff7" +
    "\017\ufff7\020\ufff7\021\ufff7\022\ufff7\023\ufff7\024\ufff7\025" +
    "\ufff7\031\ufff7\033\ufff7\036\ufff7\037\ufff7\061\ufff7\067\ufff7" +
    "\070\ufff7\071\ufff7\072\ufff7\073\ufff7\001\002\000\054\003" +
    "\ufffb\004\ufffb\015\ufffb\016\ufffb\017\ufffb\020\ufffb\021\ufffb" +
    "\022\ufffb\023\ufffb\024\ufffb\025\ufffb\031\ufffb\033\ufffb\036" +
    "\ufffb\037\ufffb\061\ufffb\067\ufffb\070\ufffb\071\ufffb\072\ufffb" +
    "\073\ufffb\001\002\000\054\003\ufff8\004\ufff8\015\ufff8\016" +
    "\ufff8\017\ufff8\020\ufff8\021\ufff8\022\ufff8\023\ufff8\024\ufff8" +
    "\025\ufff8\031\ufff8\033\ufff8\036\ufff8\037\ufff8\061\ufff8\067" +
    "\ufff8\070\ufff8\071\ufff8\072\ufff8\073\ufff8\001\002\000\054" +
    "\003\uffff\004\uffff\015\uffff\016\uffff\017\uffff\020\uffff\021" +
    "\uffff\022\uffff\023\uffff\024\uffff\025\uffff\031\uffff\033\uffff" +
    "\036\uffff\037\uffff\061\uffff\067\uffff\070\uffff\071\uffff\072" +
    "\uffff\073\uffff\001\002\000\004\064\211\001\002\000\004" +
    "\062\205\001\002\000\004\004\uffed\001\002\000\054\003" +
    "\ufffc\004\ufffc\015\ufffc\016\ufffc\017\ufffc\020\ufffc\021\ufffc" +
    "\022\ufffc\023\ufffc\024\ufffc\025\ufffc\031\ufffc\033\ufffc\036" +
    "\ufffc\037\ufffc\061\ufffc\067\ufffc\070\ufffc\071\ufffc\072\ufffc" +
    "\073\ufffc\001\002\000\004\004\176\001\002\000\004\064" +
    "\175\001\002\000\054\003\ufffd\004\ufffd\015\ufffd\016\ufffd" +
    "\017\ufffd\020\ufffd\021\ufffd\022\ufffd\023\ufffd\024\ufffd\025" +
    "\ufffd\031\ufffd\033\ufffd\036\ufffd\037\ufffd\061\ufffd\067\ufffd" +
    "\070\ufffd\071\ufffd\072\ufffd\073\ufffd\001\002\000\004\064" +
    "\174\001\002\000\004\062\165\001\002\000\004\064\164" +
    "\001\002\000\004\040\161\001\002\000\004\004\uffec\001" +
    "\002\000\004\062\126\001\002\000\054\003\ufff6\004\ufff6" +
    "\015\ufff6\016\ufff6\017\ufff6\020\ufff6\021\ufff6\022\ufff6\023" +
    "\ufff6\024\ufff6\025\ufff6\031\ufff6\033\ufff6\036\ufff6\037\ufff6" +
    "\061\ufff6\067\ufff6\070\ufff6\071\ufff6\072\ufff6\073\ufff6\001" +
    "\002\000\004\062\046\001\002\000\054\003\ufffa\004\ufffa" +
    "\015\ufffa\016\ufffa\017\ufffa\020\ufffa\021\ufffa\022\ufffa\023" +
    "\ufffa\024\ufffa\025\ufffa\031\ufffa\033\ufffa\036\ufffa\037\ufffa" +
    "\061\ufffa\067\ufffa\070\ufffa\071\ufffa\072\ufffa\073\ufffa\001" +
    "\002\000\054\003\ufff9\004\ufff9\015\ufff9\016\ufff9\017\ufff9" +
    "\020\ufff9\021\ufff9\022\ufff9\023\ufff9\024\ufff9\025\ufff9\031" +
    "\ufff9\033\ufff9\036\ufff9\037\ufff9\061\ufff9\067\ufff9\070\ufff9" +
    "\071\ufff9\072\ufff9\073\ufff9\001\002\000\004\002\000\001" +
    "\002\000\004\004\uffe9\001\002\000\024\004\060\005\051" +
    "\006\055\007\054\010\047\011\052\012\056\057\050\062" +
    "\053\001\002\000\042\041\uffc0\042\uffc0\043\uffc0\044\uffc0" +
    "\045\uffc0\046\uffc0\047\uffc0\050\uffc0\051\uffc0\052\uffc0\053" +
    "\uffc0\054\uffc0\055\uffc0\056\uffc0\063\uffc0\064\uffc0\001\002" +
    "\000\024\004\060\005\051\006\055\007\054\010\047\011" +
    "\052\012\056\057\050\062\053\001\002\000\042\041\uffc3" +
    "\042\uffc3\043\uffc3\044\uffc3\045\uffc3\046\uffc3\047\uffc3\050" +
    "\uffc3\051\uffc3\052\uffc3\053\uffc3\054\uffc3\055\uffc3\056\uffc3" +
    "\063\uffc3\064\uffc3\001\002\000\042\041\uffbf\042\uffbf\043" +
    "\uffbf\044\uffbf\045\uffbf\046\uffbf\047\uffbf\050\uffbf\051\uffbf" +
    "\052\uffbf\053\uffbf\054\uffbf\055\uffbf\056\uffbf\063\uffbf\064" +
    "\uffbf\001\002\000\024\004\060\005\051\006\055\007\054" +
    "\010\047\011\052\012\056\057\050\062\053\001\002\000" +
    "\042\041\uffc1\042\uffc1\043\uffc1\044\uffc1\045\uffc1\046\uffc1" +
    "\047\uffc1\050\uffc1\051\uffc1\052\uffc1\053\uffc1\054\uffc1\055" +
    "\uffc1\056\uffc1\063\uffc1\064\uffc1\001\002\000\042\041\uffc2" +
    "\042\uffc2\043\uffc2\044\uffc2\045\uffc2\046\uffc2\047\uffc2\050" +
    "\uffc2\051\uffc2\052\uffc2\053\uffc2\054\uffc2\055\uffc2\056\uffc2" +
    "\063\uffc2\064\uffc2\001\002\000\042\041\uffbe\042\uffbe\043" +
    "\uffbe\044\uffbe\045\uffbe\046\uffbe\047\uffbe\050\uffbe\051\uffbe" +
    "\052\uffbe\053\uffbe\054\uffbe\055\uffbe\056\uffbe\063\uffbe\064" +
    "\uffbe\001\002\000\040\041\065\042\064\043\070\044\063" +
    "\045\074\046\076\047\071\050\061\051\062\052\072\053" +
    "\066\054\077\055\075\056\067\063\073\001\002\000\042" +
    "\041\uffbd\042\uffbd\043\uffbd\044\uffbd\045\uffbd\046\uffbd\047" +
    "\uffbd\050\uffbd\051\uffbd\052\uffbd\053\uffbd\054\uffbd\055\uffbd" +
    "\056\uffbd\063\uffbd\064\uffbd\001\002\000\024\004\060\005" +
    "\051\006\055\007\054\010\047\011\052\012\056\057\050" +
    "\062\053\001\002\000\024\004\060\005\051\006\055\007" +
    "\054\010\047\011\052\012\056\057\050\062\053\001\002" +
    "\000\024\004\060\005\051\006\055\007\054\010\047\011" +
    "\052\012\056\057\050\062\053\001\002\000\024\004\060" +
    "\005\051\006\055\007\054\010\047\011\052\012\056\057" +
    "\050\062\053\001\002\000\024\004\060\005\051\006\055" +
    "\007\054\010\047\011\052\012\056\057\050\062\053\001" +
    "\002\000\024\004\060\005\051\006\055\007\054\010\047" +
    "\011\052\012\056\057\050\062\053\001\002\000\024\004" +
    "\060\005\051\006\055\007\054\010\047\011\052\012\056" +
    "\057\050\062\053\001\002\000\024\004\060\005\051\006" +
    "\055\007\054\010\047\011\052\012\056\057\050\062\053" +
    "\001\002\000\024\004\060\005\051\006\055\007\054\010" +
    "\047\011\052\012\056\057\050\062\053\001\002\000\024" +
    "\004\060\005\051\006\055\007\054\010\047\011\052\012" +
    "\056\057\050\062\053\001\002\000\004\032\104\001\002" +
    "\000\024\004\060\005\051\006\055\007\054\010\047\011" +
    "\052\012\056\057\050\062\053\001\002\000\024\004\060" +
    "\005\051\006\055\007\054\010\047\011\052\012\056\057" +
    "\050\062\053\001\002\000\024\004\060\005\051\006\055" +
    "\007\054\010\047\011\052\012\056\057\050\062\053\001" +
    "\002\000\024\004\060\005\051\006\055\007\054\010\047" +
    "\011\052\012\056\057\050\062\053\001\002\000\026\041" +
    "\065\042\064\043\070\044\063\045\074\046\076\055\uffca" +
    "\056\uffca\063\uffca\064\uffca\001\002\000\042\041\uffcf\042" +
    "\uffcf\043\uffcf\044\uffcf\045\074\046\uffcf\047\uffcf\050\uffcf" +
    "\051\uffcf\052\uffcf\053\uffcf\054\uffcf\055\uffcf\056\uffcf\063" +
    "\uffcf\064\uffcf\001\002\000\042\041\065\042\064\043\070" +
    "\044\063\045\074\046\076\047\071\050\061\051\062\052" +
    "\072\053\066\054\077\055\uffc7\056\uffc7\063\uffc7\064\uffc7" +
    "\001\002\000\042\041\uffce\042\uffce\043\uffce\044\uffce\045" +
    "\074\046\uffce\047\uffce\050\uffce\051\uffce\052\uffce\053\uffce" +
    "\054\uffce\055\uffce\056\uffce\063\uffce\064\uffce\001\002\000" +
    "\004\060\105\001\002\000\050\003\ufffe\004\ufffe\016\ufffe" +
    "\017\ufffe\020\ufffe\021\ufffe\022\ufffe\023\ufffe\024\ufffe\025" +
    "\ufffe\031\ufffe\033\ufffe\037\ufffe\061\ufffe\067\ufffe\070\ufffe" +
    "\071\ufffe\072\ufffe\073\ufffe\001\002\000\054\003\uffe2\004" +
    "\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2" +
    "\023\uffe2\024\uffe2\025\uffe2\031\uffe2\033\uffe2\036\uffe2\037" +
    "\uffe2\061\uffe2\067\uffe2\070\uffe2\071\uffe2\072\uffe2\073\uffe2" +
    "\001\002\000\050\003\034\004\035\016\025\017\036\020" +
    "\014\021\015\022\045\023\024\024\016\025\033\031\041" +
    "\033\037\037\027\061\110\067\023\070\030\071\012\072" +
    "\032\073\011\001\002\000\056\003\uffe3\004\uffe3\015\uffe3" +
    "\016\uffe3\017\uffe3\020\uffe3\021\uffe3\022\uffe3\023\uffe3\024" +
    "\uffe3\025\uffe3\027\uffe3\031\uffe3\033\uffe3\036\uffe3\037\uffe3" +
    "\061\uffe3\067\uffe3\070\uffe3\071\uffe3\072\uffe3\073\uffe3\001" +
    "\002\000\026\041\065\042\064\043\070\044\063\045\074" +
    "\046\076\055\uffcc\056\uffcc\063\uffcc\064\uffcc\001\002\000" +
    "\026\041\065\042\064\043\070\044\063\045\074\046\076" +
    "\055\uffc9\056\uffc9\063\uffc9\064\uffc9\001\002\000\042\041" +
    "\uffd1\042\uffd1\043\uffd1\044\uffd1\045\074\046\uffd1\047\uffd1" +
    "\050\uffd1\051\uffd1\052\uffd1\053\uffd1\054\uffd1\055\uffd1\056" +
    "\uffd1\063\uffd1\064\uffd1\001\002\000\042\041\065\042\064" +
    "\043\070\044\063\045\074\046\076\047\071\050\061\051" +
    "\062\052\072\053\066\054\077\055\075\056\uffc6\063\uffc6" +
    "\064\uffc6\001\002\000\026\041\065\042\064\043\070\044" +
    "\063\045\074\046\076\055\uffcb\056\uffcb\063\uffcb\064\uffcb" +
    "\001\002\000\042\041\uffd3\042\uffd3\043\070\044\063\045" +
    "\074\046\076\047\uffd3\050\uffd3\051\uffd3\052\uffd3\053\uffd3" +
    "\054\uffd3\055\uffd3\056\uffd3\063\uffd3\064\uffd3\001\002\000" +
    "\042\041\uffd2\042\uffd2\043\070\044\063\045\074\046\076" +
    "\047\uffd2\050\uffd2\051\uffd2\052\uffd2\053\uffd2\054\uffd2\055" +
    "\uffd2\056\uffd2\063\uffd2\064\uffd2\001\002\000\042\041\uffd0" +
    "\042\uffd0\043\uffd0\044\uffd0\045\074\046\uffd0\047\uffd0\050" +
    "\uffd0\051\uffd0\052\uffd0\053\uffd0\054\uffd0\055\uffd0\056\uffd0" +
    "\063\uffd0\064\uffd0\001\002\000\026\041\065\042\064\043" +
    "\070\044\063\045\074\046\076\055\uffcd\056\uffcd\063\uffcd" +
    "\064\uffcd\001\002\000\026\041\065\042\064\043\070\044" +
    "\063\045\074\046\076\055\uffc8\056\uffc8\063\uffc8\064\uffc8" +
    "\001\002\000\040\041\065\042\064\043\070\044\063\045" +
    "\074\046\076\047\071\050\061\051\062\052\072\053\066" +
    "\054\077\055\075\056\067\063\124\001\002\000\042\041" +
    "\uffc4\042\uffc4\043\uffc4\044\uffc4\045\uffc4\046\uffc4\047\uffc4" +
    "\050\uffc4\051\uffc4\052\uffc4\053\uffc4\054\uffc4\055\uffc4\056" +
    "\uffc4\063\uffc4\064\uffc4\001\002\000\042\041\065\042\064" +
    "\043\070\044\063\045\074\046\076\047\071\050\061\051" +
    "\062\052\072\053\066\054\077\055\uffc5\056\uffc5\063\uffc5" +
    "\064\uffc5\001\002\000\024\004\060\005\051\006\055\007" +
    "\054\010\047\011\052\012\056\057\050\062\053\001\002" +
    "\000\040\041\065\042\064\043\070\044\063\045\074\046" +
    "\076\047\071\050\061\051\062\052\072\053\066\054\077" +
    "\055\075\056\067\063\130\001\002\000\004\060\131\001" +
    "\002\000\004\034\134\001\002\000\010\034\134\035\153" +
    "\061\uffdc\001\002\000\010\034\uffdf\035\uffdf\061\uffdf\001" +
    "\002\000\020\004\137\005\143\006\135\007\136\010\140" +
    "\011\144\012\141\001\002\000\004\066\uffda\001\002\000" +
    "\004\066\uffd9\001\002\000\004\066\uffd5\001\002\000\004" +
    "\066\uffd8\001\002\000\004\066\uffd6\001\002\000\004\066" +
    "\145\001\002\000\004\066\uffdb\001\002\000\004\066\uffd7" +
    "\001\002\000\050\003\ufffe\004\ufffe\016\ufffe\017\ufffe\020" +
    "\ufffe\021\ufffe\022\ufffe\023\ufffe\024\ufffe\025\ufffe\031\ufffe" +
    "\033\ufffe\036\ufffe\037\ufffe\067\ufffe\070\ufffe\071\ufffe\072" +
    "\ufffe\073\ufffe\001\002\000\050\003\034\004\035\016\025" +
    "\017\036\020\014\021\015\022\045\023\024\024\016\025" +
    "\033\031\041\033\037\036\147\037\027\067\023\070\030" +
    "\071\012\072\032\073\011\001\002\000\004\064\150\001" +
    "\002\000\010\034\uffde\035\uffde\061\uffde\001\002\000\004" +
    "\061\160\001\002\000\010\034\uffe0\035\uffe0\061\uffe0\001" +
    "\002\000\004\066\154\001\002\000\050\003\ufffe\004\ufffe" +
    "\016\ufffe\017\ufffe\020\ufffe\021\ufffe\022\ufffe\023\ufffe\024" +
    "\ufffe\025\ufffe\031\ufffe\033\ufffe\036\ufffe\037\ufffe\067\ufffe" +
    "\070\ufffe\071\ufffe\072\ufffe\073\ufffe\001\002\000\050\003" +
    "\034\004\035\016\025\017\036\020\014\021\015\022\045" +
    "\023\024\024\016\025\033\031\041\033\037\036\156\037" +
    "\027\067\023\070\030\071\012\072\032\073\011\001\002" +
    "\000\004\064\157\001\002\000\004\061\uffdd\001\002\000" +
    "\054\003\uffe1\004\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1" +
    "\021\uffe1\022\uffe1\023\uffe1\024\uffe1\025\uffe1\031\uffe1\033" +
    "\uffe1\036\uffe1\037\uffe1\061\uffe1\067\uffe1\070\uffe1\071\uffe1" +
    "\072\uffe1\073\uffe1\001\002\000\024\004\060\005\051\006" +
    "\055\007\054\010\047\011\052\012\056\057\050\062\053" +
    "\001\002\000\040\041\065\042\064\043\070\044\063\045" +
    "\074\046\076\047\071\050\061\051\062\052\072\053\066" +
    "\054\077\055\075\056\067\064\163\001\002\000\054\003" +
    "\uffe8\004\uffe8\015\uffe8\016\uffe8\017\uffe8\020\uffe8\021\uffe8" +
    "\022\uffe8\023\uffe8\024\uffe8\025\uffe8\031\uffe8\033\uffe8\036" +
    "\uffe8\037\uffe8\061\uffe8\067\uffe8\070\uffe8\071\uffe8\072\uffe8" +
    "\073\uffe8\001\002\000\054\003\ufff5\004\ufff5\015\ufff5\016" +
    "\ufff5\017\ufff5\020\ufff5\021\ufff5\022\ufff5\023\ufff5\024\ufff5" +
    "\025\ufff5\031\ufff5\033\ufff5\036\ufff5\037\ufff5\061\ufff5\067" +
    "\ufff5\070\ufff5\071\ufff5\072\ufff5\073\ufff5\001\002\000\024" +
    "\004\060\005\051\006\055\007\054\010\047\011\052\012" +
    "\056\057\050\062\053\001\002\000\040\041\065\042\064" +
    "\043\070\044\063\045\074\046\076\047\071\050\061\051" +
    "\062\052\072\053\066\054\077\055\075\056\067\063\167" +
    "\001\002\000\004\026\170\001\002\000\004\060\105\001" +
    "\002\000\056\003\uffe5\004\uffe5\015\uffe5\016\uffe5\017\uffe5" +
    "\020\uffe5\021\uffe5\022\uffe5\023\uffe5\024\uffe5\025\uffe5\027" +
    "\172\031\uffe5\033\uffe5\036\uffe5\037\uffe5\061\uffe5\067\uffe5" +
    "\070\uffe5\071\uffe5\072\uffe5\073\uffe5\001\002\000\004\060" +
    "\105\001\002\000\054\003\uffe4\004\uffe4\015\uffe4\016\uffe4" +
    "\017\uffe4\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025" +
    "\uffe4\031\uffe4\033\uffe4\036\uffe4\037\uffe4\061\uffe4\067\uffe4" +
    "\070\uffe4\071\uffe4\072\uffe4\073\uffe4\001\002\000\054\003" +
    "\ufff1\004\ufff1\015\ufff1\016\ufff1\017\ufff1\020\ufff1\021\ufff1" +
    "\022\ufff1\023\ufff1\024\ufff1\025\ufff1\031\ufff1\033\ufff1\036" +
    "\ufff1\037\ufff1\061\ufff1\067\ufff1\070\ufff1\071\ufff1\072\ufff1" +
    "\073\ufff1\001\002\000\054\003\ufff3\004\ufff3\015\ufff3\016" +
    "\ufff3\017\ufff3\020\ufff3\021\ufff3\022\ufff3\023\ufff3\024\ufff3" +
    "\025\ufff3\031\ufff3\033\ufff3\036\ufff3\037\ufff3\061\ufff3\067" +
    "\ufff3\070\ufff3\071\ufff3\072\ufff3\073\ufff3\001\002\000\004" +
    "\062\177\001\002\000\004\004\200\001\002\000\004\063" +
    "\201\001\002\000\004\040\202\001\002\000\024\004\060" +
    "\005\051\006\055\007\054\010\047\011\052\012\056\057" +
    "\050\062\053\001\002\000\040\041\065\042\064\043\070" +
    "\044\063\045\074\046\076\047\071\050\061\051\062\052" +
    "\072\053\066\054\077\055\075\056\067\064\204\001\002" +
    "\000\054\003\uffd4\004\uffd4\015\uffd4\016\uffd4\017\uffd4\020" +
    "\uffd4\021\uffd4\022\uffd4\023\uffd4\024\uffd4\025\uffd4\031\uffd4" +
    "\033\uffd4\036\uffd4\037\uffd4\061\uffd4\067\uffd4\070\uffd4\071" +
    "\uffd4\072\uffd4\073\uffd4\001\002\000\024\004\060\005\051" +
    "\006\055\007\054\010\047\011\052\012\056\057\050\062" +
    "\053\001\002\000\040\041\065\042\064\043\070\044\063" +
    "\045\074\046\076\047\071\050\061\051\062\052\072\053" +
    "\066\054\077\055\075\056\067\063\207\001\002\000\004" +
    "\064\210\001\002\000\054\003\uffe7\004\uffe7\015\uffe7\016" +
    "\uffe7\017\uffe7\020\uffe7\021\uffe7\022\uffe7\023\uffe7\024\uffe7" +
    "\025\uffe7\031\uffe7\033\uffe7\036\uffe7\037\uffe7\061\uffe7\067" +
    "\uffe7\070\uffe7\071\uffe7\072\uffe7\073\uffe7\001\002\000\054" +
    "\003\ufff4\004\ufff4\015\ufff4\016\ufff4\017\ufff4\020\ufff4\021" +
    "\ufff4\022\ufff4\023\ufff4\024\ufff4\025\ufff4\031\ufff4\033\ufff4" +
    "\036\ufff4\037\ufff4\061\ufff4\067\ufff4\070\ufff4\071\ufff4\072" +
    "\ufff4\073\ufff4\001\002\000\004\004\213\001\002\000\004" +
    "\063\214\001\002\000\004\064\215\001\002\000\054\003" +
    "\uffe6\004\uffe6\015\uffe6\016\uffe6\017\uffe6\020\uffe6\021\uffe6" +
    "\022\uffe6\023\uffe6\024\uffe6\025\uffe6\031\uffe6\033\uffe6\036" +
    "\uffe6\037\uffe6\061\uffe6\067\uffe6\070\uffe6\071\uffe6\072\uffe6" +
    "\073\uffe6\001\002\000\006\040\220\064\217\001\002\000" +
    "\054\003\uffef\004\uffef\015\uffef\016\uffef\017\uffef\020\uffef" +
    "\021\uffef\022\uffef\023\uffef\024\uffef\025\uffef\031\uffef\033" +
    "\uffef\036\uffef\037\uffef\061\uffef\067\uffef\070\uffef\071\uffef" +
    "\072\uffef\073\uffef\001\002\000\024\004\060\005\051\006" +
    "\055\007\054\010\047\011\052\012\056\057\050\062\053" +
    "\001\002\000\040\041\065\042\064\043\070\044\063\045" +
    "\074\046\076\047\071\050\061\051\062\052\072\053\066" +
    "\054\077\055\075\056\067\064\222\001\002\000\054\003" +
    "\uffee\004\uffee\015\uffee\016\uffee\017\uffee\020\uffee\021\uffee" +
    "\022\uffee\023\uffee\024\uffee\025\uffee\031\uffee\033\uffee\036" +
    "\uffee\037\uffee\061\uffee\067\uffee\070\uffee\071\uffee\072\uffee" +
    "\073\uffee\001\002\000\054\003\ufff2\004\ufff2\015\ufff2\016" +
    "\ufff2\017\ufff2\020\ufff2\021\ufff2\022\ufff2\023\ufff2\024\ufff2" +
    "\025\ufff2\031\ufff2\033\ufff2\036\ufff2\037\ufff2\061\ufff2\067" +
    "\ufff2\070\ufff2\071\ufff2\072\ufff2\073\ufff2\001\002\000\054" +
    "\003\ufff0\004\ufff0\015\ufff0\016\ufff0\017\ufff0\020\ufff0\021" +
    "\ufff0\022\ufff0\023\ufff0\024\ufff0\025\ufff0\031\ufff0\033\ufff0" +
    "\036\ufff0\037\ufff0\061\ufff0\067\ufff0\070\ufff0\071\ufff0\072" +
    "\ufff0\073\ufff0\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\223\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\007\001\001" +
    "\000\026\004\021\005\030\006\025\007\017\010\041\011" +
    "\042\012\020\013\016\017\037\021\012\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\022" +
    "\056\001\001\000\002\001\001\000\004\022\124\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\022\122\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\022\121\001" +
    "\001\000\004\022\120\001\001\000\004\022\117\001\001" +
    "\000\004\022\116\001\001\000\004\022\115\001\001\000" +
    "\004\022\114\001\001\000\004\022\113\001\001\000\004" +
    "\022\112\001\001\000\004\022\111\001\001\000\004\022" +
    "\110\001\001\000\002\001\001\000\004\022\102\001\001" +
    "\000\004\022\101\001\001\000\004\022\100\001\001\000" +
    "\004\022\077\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\020\105\001" +
    "\001\000\004\003\106\001\001\000\002\001\001\000\026" +
    "\004\021\005\030\006\025\007\017\010\041\011\042\012" +
    "\020\013\016\017\037\021\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\022\126\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\014\131\015\132\001\001\000\006\015\151" +
    "\016\150\001\001\000\002\001\001\000\004\023\141\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\145\001\001" +
    "\000\026\004\021\005\030\006\025\007\017\010\041\011" +
    "\042\012\020\013\016\017\037\021\012\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\154\001\001\000\026" +
    "\004\021\005\030\006\025\007\017\010\041\011\042\012" +
    "\020\013\016\017\037\021\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\022\161\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\022\165\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\020\170\001\001\000\002\001\001\000\004" +
    "\020\172\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\022\202\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\022\205\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\220\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public StringBuilder reporte = new StringBuilder();

    @Override
    public void syntax_error(Symbol s) {
        String valor = (s.value == null) ? "sin valor" : s.value.toString();

        String mensaje = "Error sintáctico en línea " + s.left
                + ", columna " + s.right
                + ". Símbolo recibido: " + valor;

        System.err.println(mensaje);
        reporte.append(mensaje).append("\\n");
    }

    @Override
    public void unrecovered_syntax_error(Symbol s) throws Exception {
        String mensaje = "Error sintáctico no recuperable en línea " + s.left
                + ", columna " + s.right + ".";

        System.err.println(mensaje);
        reporte.append(mensaje).append("\\n");
        throw new Exception(mensaje);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCup$actions {
  private final ParserCup parser;

  /** Constructor */
  CUP$ParserCup$actions(ParserCup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action_part00000000(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCup$result;

      /* select the action based on the action number */
      switch (CUP$ParserCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		RESULT = start_val;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCup$parser.done_parsing();
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= PROGRAMA IDENTIFICADOR INICIO lista_instrucciones FIN 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_instrucciones ::= lista_instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_instrucciones ::= 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= declaracion 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= asignacion 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= imprimir 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= leer 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= si 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= mientras 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= evaluar 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= graficar 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion ::= error FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // instruccion ::= ERROR FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instruccion ::= ERROR_CADENA FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // instruccion ::= ERROR_CARACTER FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // instruccion ::= ERROR_NUMERO FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // instruccion ::= ERROR_IDENTIFICADOR FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracion ::= tipo IDENTIFICADOR FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracion ::= tipo IDENTIFICADOR OP_ASIG expr FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= TIPO_ENTERO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("tipo",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // tipo ::= TIPO_REAL 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("tipo",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipo ::= TIPO_CADENA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("tipo",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo ::= TIPO_CARACTER 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("tipo",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo ::= TIPO_LOGICO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("tipo",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // asignacion ::= IDENTIFICADOR OP_ASIG expr FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // imprimir ::= IMPRIMIR PARENT_ABRE expr PARENT_CIERRA FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("imprimir",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // leer ::= LEER PARENT_ABRE IDENTIFICADOR PARENT_CIERRA FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("leer",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // si ::= SI PARENT_ABRE expr PARENT_CIERRA ENTONCES bloque 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("si",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // si ::= SI PARENT_ABRE expr PARENT_CIERRA ENTONCES bloque SINO bloque 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("si",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // bloque ::= LLAVE_ABRE lista_instrucciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloque",14, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // mientras ::= MIENTRAS PARENT_ABRE expr PARENT_CIERRA HACER bloque 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("mientras",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // evaluar ::= EVALUAR PARENT_ABRE expr PARENT_CIERRA LLAVE_ABRE lista_casos caso_otro LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("evaluar",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_casos ::= lista_casos caso 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("lista_casos",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_casos ::= caso 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("lista_casos",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // caso ::= CASO valor_caso DOS_PUNTOS lista_instrucciones PARAR FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("caso",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // caso_otro ::= OTRO DOS_PUNTOS lista_instrucciones PARAR FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("caso_otro",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // caso_otro ::= 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("caso_otro",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // valor_caso ::= NUMERO_ENTERO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("valor_caso",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // valor_caso ::= NUMERO_REAL 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("valor_caso",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // valor_caso ::= VALOR_CADENA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("valor_caso",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // valor_caso ::= VALOR_CARACTER 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("valor_caso",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // valor_caso ::= VALOR_VERDADERO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("valor_caso",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // valor_caso ::= VALOR_FALSO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("valor_caso",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // valor_caso ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("valor_caso",17, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // graficar ::= GRAFICAR IDENTIFICADOR PARENT_ABRE IDENTIFICADOR PARENT_CIERRA OP_ASIG expr FIN_SENTENCIA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("graficar",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr OP_SUMA expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr OP_RESTA expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr OP_MULT expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr OP_DIV expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr OP_MOD expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= expr OP_POT expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= expr MAYOR_QUE expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= expr MENOR_QUE expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= expr MAYOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= expr MENOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= expr IGUAL_QUE expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= expr DIFERENTE_QUE expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= expr OP_Y expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= expr OP_O expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= OP_NO expr 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= PARENT_ABRE expr PARENT_CIERRA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= NUMERO_ENTERO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= NUMERO_REAL 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= VALOR_CADENA 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= VALOR_CARACTER 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= VALOR_VERDADERO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr ::= VALOR_FALSO 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expr",16, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
              return CUP$ParserCup$do_action_part00000000(
                               CUP$ParserCup$act_num,
                               CUP$ParserCup$parser,
                               CUP$ParserCup$stack,
                               CUP$ParserCup$top);
    }
}

}
